# Generated by Django 5.1.3 on 2025-01-22 15:01

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("myapp", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="event_request",
            name="response_status",
            field=models.CharField(
                choices=[
                    ("pending", "รอการตอบกลับ"),
                    ("accepted", "อนุมัติ"),
                    ("rejected", "ปฏิเสธ"),
                ],
                default="pending",
                max_length=10,
            ),
        ),
    ]
