# Generated by Django 5.1.3 on 2025-01-22 16:37

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("myapp", "0002_alter_event_request_response_status"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="report",
            options={
                "ordering": ["-created_at"],
                "verbose_name": "รายงาน",
                "verbose_name_plural": "รายงานทั้งหมด",
            },
        ),
        migrations.AlterField(
            model_name="report",
            name="event_owner",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="events_owned",
                to=settings.AUTH_USER_MODEL,
                verbose_name="เจ้าของอีเวนต์",
            ),
        ),
        migrations.AlterField(
            model_name="report",
            name="is_warned",
            field=models.CharField(
                choices=[
                    ("รอดำเนินการ", "รอดำเนินการ"),
                    ("เตือนผู้ใช้งาน", "เตือนผู้ใช้งาน"),
                    ("ปฏิเสธการรายงาน", "ปฏิเสธการรายงาน"),
                ],
                default="รอดำเนินการ",
                max_length=15,
                verbose_name="สถานะการแจ้งเตือน",
            ),
        ),
    ]
