# Generated by Django 5.1.3 on 2025-01-23 15:42

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("myapp", "0005_member_is_banned"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="member",
            name="is_banned",
        ),
    ]
