# Generated by Django 5.1.3 on 2025-01-23 15:42

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("myapp", "0006_remove_member_is_banned"),
    ]

    operations = [
        migrations.AddField(
            model_name="member",
            name="is_banned",
            field=models.BooleanField(default=False),
        ),
    ]
