# Generated by Django 5.1.3 on 2025-01-24 06:47

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("myapp", "0009_alter_event_province"),
    ]

    operations = [
        migrations.AlterField(
            model_name="event",
            name="province",
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name="report",
            name="report_type",
            field=models.CharField(
                choices=[
                    ("ความผิดพลาดของระบบ", "ความผิดพลาดของระบบ"),
                    ("พฤติกรรมไม่เหมาะสม", "พฤติกรรมไม่เหมาะสม"),
                    ("อื่นๆ", "อื่นๆ"),
                ],
                max_length=50,
                null=True,
                verbose_name="ประเภทการรายงาน",
            ),
        ),
    ]
