# Generated by Django 5.1.3 on 2025-01-24 10:44

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("myapp", "0011_event_is_active_event_is_banned"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="event",
            name="is_active",
        ),
        migrations.RemoveField(
            model_name="event",
            name="is_banned",
        ),
    ]
