# Generated by Django 5.1.3 on 2025-01-24 11:00

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("myapp", "0012_remove_event_is_active_remove_event_is_banned"),
    ]

    operations = [
        migrations.AddField(
            model_name="event",
            name="is_active",
            field=models.BooleanField(default=True),
        ),
    ]
