# Generated by Django 5.1.3 on 2025-01-24 15:24

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("myapp", "0013_event_is_active"),
    ]

    operations = [
        migrations.AddField(
            model_name="notification",
            name="is_active",
            field=models.BooleanField(default=True),
        ),
    ]
