# Generated by Django 5.1.3 on 2025-01-24 16:12

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("myapp", "0014_notification_is_active"),
    ]

    operations = [
        migrations.AlterField(
            model_name="notification",
            name="notification_type",
            field=models.CharField(
                choices=[
                    ("คำขอเข้าร่วมกิจกรรม", "คำขอเข้าร่วมกิจกรรม"),
                    ("ตอบกลับคำขอ", "ตอบกลับคำขอ"),
                    ("อื่น ๆ", "อื่น ๆ"),
                ],
                default="other",
                max_length=20,
            ),
        ),
    ]
