# Generated by Django 5.1.3 on 2025-01-24 16:12

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("myapp", "0015_alter_notification_notification_type"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="notification",
            name="is_active",
        ),
    ]
