# Generated by Django 5.1.3 on 2025-01-25 08:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("myapp", "0016_remove_notification_is_active"),
    ]

    operations = [
        migrations.AddField(
            model_name="notification",
            name="related_request",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="myapp.event_request",
            ),
        ),
    ]
