# Generated by Django 5.1.3 on 2025-01-25 10:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("myapp", "0017_notification_related_request"),
    ]

    operations = [
        migrations.AlterField(
            model_name="event_request",
            name="event",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="event_requests",
                to="myapp.event",
            ),
        ),
    ]
