# Generated by Django 5.1.3 on 2025-01-25 14:13

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("myapp", "0018_alter_event_request_event"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="message",
            name="chatroom",
        ),
        migrations.RemoveField(
            model_name="message",
            name="sender",
        ),
        migrations.AlterField(
            model_name="event",
            name="category",
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name="event",
            name="event_name",
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name="event",
            name="location",
            field=models.CharField(max_length=100),
        ),
        migrations.DeleteModel(
            name="ChatRoom",
        ),
        migrations.DeleteModel(
            name="Message",
        ),
    ]
