# Generated by Django 5.1.3 on 2025-01-25 15:03

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("myapp", "0020_chatroom"),
    ]

    operations = [
        migrations.DeleteModel(
            name="ChatRoom",
        ),
    ]
