# Generated by Django 5.1.3 on 2025-01-25 15:07

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("myapp", "0022_chatroom"),
    ]

    operations = [
        migrations.AlterField(
            model_name="chatroom",
            name="members",
            field=models.ManyToManyField(
                blank=True, related_name="chat_rooms", to=settings.AUTH_USER_MODEL
            ),
        ),
    ]
