# Generated by Django 5.1.3 on 2025-01-25 16:04

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("myapp", "0023_alter_chatroom_members"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="chatroom",
            name="name",
        ),
    ]
