# Generated by Django 5.1.5 on 2025-01-27 15:51

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("myapp", "0026_participant"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="event_request",
            options={"ordering": ["-request_time"]},
        ),
        migrations.RemoveIndex(
            model_name="event_request",
            name="myapp_event_event_i_ce261c_idx",
        ),
    ]
