# Generated by Django 5.1.3 on 2025-01-27 18:46

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("myapp", "0027_alter_event_request_options_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="chatroom",
            name="updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
    ]
