# Generated by Django 5.1.3 on 2025-01-27 18:55

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("myapp", "0028_chatroom_updated_at"),
    ]

    operations = [
        migrations.AddField(
            model_name="chat_message",
            name="is_system_message",
            field=models.BooleanField(default=False),
        ),
    ]
