# Generated by Django 5.1.5 on 2025-01-29 15:06

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("myapp", "0030_alter_chat_message_sender"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="chat_message",
            options={"ordering": ["created_at"]},
        ),
    ]
