# Generated by Django 5.1.5 on 2025-01-30 10:31

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("myapp", "0034_eventreview_delete_participant"),
    ]

    operations = [
        migrations.AddField(
            model_name="event",
            name="has_ended",
            field=models.BooleanField(default=False),
        ),
    ]
