# Generated by Django 5.1.5 on 2025-01-30 19:15

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("myapp", "0035_event_has_ended"),
    ]

    operations = [
        migrations.AddField(
            model_name="notification",
            name="is_sent",
            field=models.BooleanField(default=False),
        ),
    ]
