# Generated by Django 5.1.5 on 2025-02-01 14:01

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("myapp", "0037_alter_notification_is_sent"),
    ]

    operations = [
        migrations.AlterField(
            model_name="event",
            name="has_ended",
            field=models.BooleanField(default=True),
        ),
    ]
