# Generated by Django 5.1.5 on 2025-02-01 14:20

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("myapp", "0038_alter_event_has_ended"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="notification",
            name="is_sent",
        ),
    ]
