# Generated by Django 5.1.5 on 2025-02-01 16:02

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("myapp", "0039_remove_notification_is_sent"),
    ]

    operations = [
        migrations.AlterField(
            model_name="event",
            name="has_ended",
            field=models.BooleanField(default=False),
        ),
    ]
