# Generated by Django 5.1.5 on 2025-02-04 10:14

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("myapp", "0041_notification_is_scheduled_and_more"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="EventReview",
            new_name="Event_Review",
        ),
    ]
