# Generated by Django 5.1.5 on 2025-03-02 11:28

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("myapp", "0042_rename_eventreview_event_review"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Advertisement",
        ),
        migrations.AlterField(
            model_name="event",
            name="category",
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name="event",
            name="event_name",
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name="event",
            name="location",
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name="event",
            name="province",
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name="event_request",
            name="response_status",
            field=models.CharField(
                choices=[
                    ("pending", "รอการตอบกลับ"),
                    ("accepted", "อนุมัติ"),
                    ("rejected", "ปฏิเสธ"),
                ],
                default="pending",
                max_length=12,
            ),
        ),
        migrations.AlterField(
            model_name="event_review",
            name="comment",
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name="member",
            name="description",
            field=models.CharField(
                blank=True, default="เพิ่มคำอธิบายของคุณ", max_length=50, null=True
            ),
        ),
        migrations.DeleteModel(
            name="User",
        ),
    ]
