# Generated by Django 5.1.5 on 2025-03-05 15:18

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("myapp", "0044_alter_event_category"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="notification",
            name="scheduled_time",
        ),
        migrations.AlterField(
            model_name="chat_message",
            name="message",
            field=models.CharField(max_length=100),
        ),
    ]
