# Generated by Django 5.2.4 on 2025-07-16 12:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0045_remove_notification_scheduled_time_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='event_end_datetime',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
