# Generated by Django 5.2.4 on 2025-07-17 13:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0047_identityverification'),
    ]

    operations = [
        migrations.RenameField(
            model_name='identityverification',
            old_name='user',
            new_name='member',
        ),
    ]
