# Generated by Django 5.2.4 on 2025-07-17 13:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0048_rename_user_identityverification_member'),
    ]

    operations = [
        migrations.RenameField(
            model_name='identityverification',
            old_name='member',
            new_name='user',
        ),
    ]
