# Generated by Django 5.2.4 on 2025-07-17 20:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0050_member_facebook_member_instagram_member_line_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='facebook',
            field=models.URLField(blank=True, default='เพิ่มลิงก์ของคุณ', null=True),
        ),
        migrations.AlterField(
            model_name='member',
            name='instagram',
            field=models.URLField(blank=True, default='เพิ่มลิงก์ของคุณ', null=True),
        ),
        migrations.AlterField(
            model_name='member',
            name='line_id',
            field=models.CharField(blank=True, default='เพิ่มไอดีของคุณ', max_length=50, null=True),
        ),
    ]
