# Generated by Django 5.2.4 on 2025-07-17 22:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0051_alter_member_facebook_alter_member_instagram_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='identityverification',
            name='document',
        ),
        migrations.AddField(
            model_name='identityverification',
            name='id_card_image',
            field=models.ImageField(blank=True, null=True, upload_to='id_documents/'),
        ),
        migrations.AddField(
            model_name='identityverification',
            name='selfie_image',
            field=models.ImageField(blank=True, null=True, upload_to='id_documents/selfie/'),
        ),
    ]
