# Generated by Django 5.2.4 on 2025-07-17 23:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0052_remove_identityverification_document_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='member',
            name='facebook',
        ),
        migrations.RemoveField(
            model_name='member',
            name='instagram',
        ),
        migrations.RemoveField(
            model_name='member',
            name='line_id',
        ),
    ]
